const data = [
  { savol: "O‘zbekistonning poytaxti qayer?", javob: "Toshkent" },
  { savol: "Yerning sun’iy yo‘ldoshi nima deb ataladi?", javob: "Oy" },
  { savol: "Amir Temur qachon tug‘ilgan?", javob: "1336-yil 9-aprel" },
  { savol: "Dunyoning eng baland tog‘i qaysi?", javob: "Everest" },
  { savol: "O‘zbekiston Respublikasi bayrog‘ida nechta rang bor?", javob: "Uchta" },
  { savol: "Sharq Arastusi kim?", javob: "Abu Nasr Forobiy" },
  { savol: "Inson yuragida nechta bo‘lmacha mavjud?", javob: "To‘rt" },
  { savol: "Elektr tokini o‘lchash birligi nima?", javob: "Amper" },
  { savol: "O‘zbekistonning milliy valyutasi nima?", javob: "So‘m" },
  { savol: "Fotosintez qaysi mavjudotlarda sodir bo‘ladi?", javob: "O‘simliklarda" },
  { savol: "O‘zbekiston mustaqillikka qachon erishgan?", javob: "1991-yil 1-sentabr" },
  { savol: "Atom raqami 1 bo‘lgan element qaysi?", javob: "Vodorod" },
  { savol: "Yer Quyosh atrofini necha kunda aylanib chiqadi?", javob: "365 kun" },
  { savol: "Qaysi shahar qadimda Afrosiyob nomi bilan mashhur bo‘lgan?", javob: "Samarqand" },
  { savol: "O‘zbekistonning eng katta ko‘li qaysi?", javob: "Aral dengizi" },
  { savol: "Hujayra yadrosida nima joylashgan?", javob: "DNK" },
  { savol: "Buyuk Ipak yo‘li qaysi mamlakatlarni bog‘lagan?", javob: "Xitoy va Yevropa" },
  { savol: "Zahiriddin Muhammad Bobur kim edi?", javob: "Shoir va sarkarda" },
  { savol: "O‘zbekiston davlat madhiyasi muallifi kim?", javob: "Abdulla Oripov" },
  { savol: "Alisher Navoiy qaysi tilni mukammal bilgan?", javob: "Chig‘atoy tili" },
  { savol: "Столица России?", javob: "Москва" },
  { savol: "Сколько океанов на Земле?", javob: "Пять" },
  { savol: "Когда началась Вторая мировая война?", javob: "1 сентября 1939 года" },
  { savol: "Кто написал роман 'Война и мир'?", javob: "Лев Толстой" },
  { savol: "Самая длинная река в мире?", javob: "Нил" },
  { savol: "Какой газ необходим для дыхания?", javob: "Кислород" },
  { savol: "Первый человек в космосе?", javob: "Юрий Гагарин" },
  { savol: "Химический символ золота?", javob: "Au" },
  { savol: "Какое море самое солёное?", javob: "Мёртвое море" },
  { savol: "Кто автор произведения 'Ревизор'?", javob: "Николай Гоголь" },
  { savol: "Сколько планет в Солнечной системе?", javob: "Восемь" },
  { savol: "Кто изобрёл радио?", javob: "Александр Попов" },
  { savol: "Столица Франции?", javob: "Париж" },
  { savol: "Когда распался СССР?", javob: "1991 год" },
  { savol: "Какая наука изучает живые организмы?", javob: "Биология" },
  { savol: "Сколько хромосом у человека?", javob: "46" },
  { savol: "Кто написал 'Евгений Онегин'?", javob: "Александр Pushkin" },
  { savol: "Какая самая высокая гора России?", javob: "Эльбрус" },
  { savol: "Что изобрёл Дмитрий Менделеев?", javob: "Периодическая таблица" },
  { savol: "Столица Казахстана?", javob: "Астана" },
  { savol: "What is the capital of the United Kingdom?", javob: "London" },
  { savol: "Who developed the theory of relativity?", javob: "Albert Einstein" },
  { savol: "Which planet is known as the Red Planet?", javob: "Mars" },
  { savol: "What is the largest mammal on Earth?", javob: "Blue Whale" },
  { savol: "Who painted the Mona Lisa?", javob: "Leonardo da Vinci" },
  { savol: "What is the boiling point of water at sea level?", javob: "100°C" },
  { savol: "Which is the longest river in the world?", javob: "Nile" },
  { savol: "Who was the first President of the USA?", javob: "George Washington" },
  { savol: "What is the chemical formula of water?", javob: "H2O" },
  { savol: "Which continent is the Sahara Desert located in?", javob: "Africa" },
  { savol: "Who is known as the father of computers?", javob: "Charles Babbage" },
  { savol: "What is the capital city of Japan?", javob: "Tokyo" },
  { savol: "Which gas do humans exhale?", javob: "Carbon dioxide" },
  { savol: "In which year did World War I begin?", javob: "1914" },
  { savol: "What is the hardest natural substance?", javob: "Diamond" },
  { savol: "Which language has the most native speakers?", javob: "Mandarin Chinese" },
  { savol: "What is the fastest land animal?", javob: "Cheetah" },
  { savol: "Which organ in the human body pumps blood?", javob: "Heart" },
  { savol: "What is the capital of Italy?", javob: "Rome" },
  { savol: "Who discovered penicillin?", javob: "Alexander Fleming" }
];
